### ISSUE TITLE
开源的也来造谣？有证据麻烦贴出来，你这是怕别人把你的钱赚走了吧

### ISSUE THREAD

**Issue by jiajia4451** [gpcoolboy/noscription#1]
这个是键盘记录，盗取密钥的，怎么举报，大家不要上当。

**Comment by gpcoolboy** [comment]
兄弟，造谣要负责啊，代码明明白白的摆着，哪一行是键盘记录的你指给我看

**Comment by jiajia4451** [comment]
https://github.com/gpcoolboy/noscription/releases/download/release/mint.exe
![image](https://github.com/gpcoolboy/noscription/assets/85436808/27ce73f3-d130-4d6b-8cee-368e09840d3c)
![image](https://github.com/gpcoolboy/noscription/assets/85436808/87e82a00-e7a6-4d88-8770-3b30f8de6c1c)
https://www.virscan.org/report/3644c0815f0973c6ddeeb06402fd0f755f214ada8e175e6aaa4ce7eb5268d639
