### ISSUE TITLE
这个是键盘记录，它自己打包的那个exe，骗子死全家，删帖死妈

### ISSUE THREAD

**Issue by jiajia4451** [gpcoolboy/noscription#2]
https://github.com/gpcoolboy/noscription/releases/download/release/mint.exe
![image](https://github.com/gpcoolboy/noscription/assets/85436808/27ce73f3-d130-4d6b-8cee-368e09840d3c)
![image](https://github.com/gpcoolboy/noscription/assets/85436808/87e82a00-e7a6-4d88-8770-3b30f8de6c1c)
https://www.virscan.org/report/3644c0815f0973c6ddeeb06402fd0f755f214ada8e175e6aaa4ce7eb5268d639

**Comment by jiajia4451** [comment]
就你这种败类，如果不是病毒，别删我帖子，让大家来评理，删帖不是心虚？

**Comment by gpcoolboy** [comment]
第一，我没有删帖，你的帖子在已解决里面，第二，你要觉得我打包的exe有问题，你可以自己打包，README.md里我写了方法，之所以打包是因为一般人自己配环境很麻烦。我不知道这种检测软件报的是什么意思，稍微懂一点编程的看了就能懂，我引用的selenium包是操控浏览器的，并没有记录键盘行为的组件。
